### PR TITLE
Updated UI For The Application

### PR DESCRIPTION
**Pull request by 0211AB**
Hello Guys,
I am Abhay Bajaj, a 2024 graduate from Jadavpur University (IT) and a fellow coder on Leetcode . I came across one of your posts on LinkedIn regarding the LC Police application that you guys have created. I believe the work that you have done is very noble and commendable. Although the core USP of your product is not the UI, but when I went on the app, the UI was not very attractive as well.

Since there is some time in my joining and I was free right now, I decided to do a small UI revamp for the application. Hope you guys like the UI and accept this pull request. I have attached some screenshots of how the new UI looks. Keep up the good work irrespective !!!

Screenshot 2024-07-11 234345

Screenshot 2024-07-11 234355

Screenshot 2024-07-11 234408

### CODE REVIEW

**Comment by theMitocondria** [comment]
First of all , Thanks a lot Abhay.
I am really glad you made this great UI and will surely merge all of these
by Sunday and will consult you for further changes.
Regards
Dhruv Mehta
9319014580

**Comment by theMitocondria** [comment]
Hello Abhay ,
There are some issues with your frontend :
1. The prrview code is taking whole screen in phones and user can not exit it .
2. Text in code needs to be a little small
3. Even on Laptop screen the code blocks are large and 110-125% zoom close option is not seen so it could be issue
4. We want you to add a contributor section and your linkedin in that rather than instagram , and that section would replace the bottom section of credits , If you can do these changes let us know .

**Comment by 0211AB** [comment]
> Hello Abhay , There are some issues with your frontend :
> 
> 1. The prrview code is taking whole screen in phones and user can not exit it .
> 2. Text in code needs to be a little small
> 3. Even on Laptop screen the code blocks are large and 110-125% zoom close option is not seen so it could be issue
> 4. We want you to add a contributor section and your linkedin in that rather than instagram , and that section would replace the bottom section of credits , If you can do these changes let us know .

Sure Dhruv, I will try to do these changes and update by today EOD.

**Comment by theMitocondria** [comment]
Hello Abhay ,
We are beyond happy to see someone so good contibuting to our repository . But due to lots of errors in backend we have to change our backend schemas hence , some state management , context api changes need to be made .

We would really love to add you as a contributor but now we do not have a lot of time before our next contest . So if you really want your UI to be implemented as a contributor , then please let us know by tomorrow afternoon that is before 14 : 00 (2:00 PM IST ) 16 July 2024 . So that we can converse on a chat / call / meet for further advancemnt if you are willing to do so .

But if you are not comfortable with this deadline we need to move further without your UI.Thanks a lot for considering our repo for your valuable contibutions we really appreciate your enthusiam .

**Comment by 0211AB** [comment]
Hi Dhruv, I was busy in a friends wedding for the last 2 days hence the delay. Do you want to connect via call first or should I work on the changes directly?

**Comment by theMitocondria** [comment]
Thanks a lot for this commendable work . We will further see u as a contributor for any help .

**Comment by theMitocondria** [comment]
[Screencast from 16-07-24 09:11:28 AM IST.webm](https://github.com/user-attachments/assets/13dfa59d-4370-4eed-90de-77c67a3e5b9d)
Thanks for the amazing UI i have attached the video of changed UI. If you like now you can show it off on your LinkedIn and all. Just mention us so we can comment on it too.

**Pull request merged**
